# For Fleet Free:
# - This file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium:
# - This file updates policies and queries that run on all hosts ("All fleets").
# - Remove "controls" and add this to your YAML files in fleets/ instead.

policies:
  # macOS policies
  - paths: ./lib/macos/policies/*.yml
  # Linux policies
  # - paths: ./lib/linux/policies/*.yml
queries:
  - paths: ./lib/macos/queries/*.yml
  - paths: ./lib/all/queries/*.yml

agent_options:
  path: ./lib/all/agent-options/agent-options.yml
  config:
    decorators:
      load:
        - SELECT uuid AS host_uuid FROM system_info;
        - SELECT hostname AS hostname FROM system_info;
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: "Declarative Management (ds)"
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  features:
    enable_host_users: true
    enable_software_inventory: true
  mdm:
    macos_setup:
      macos_setup_assistant: ./lib/macos/enrollment-profiles/automatic-enrollment.dep.json
    end_user_license_agreement: ./lib/macos/misc/eula.pdf
    end_user_authentication:
      entity_id: fleet
      idp_name: Okta
      metadata_url: https://trial-5568133.okta.com/app/exkxzb4y1mD65dJih697/sso/saml/metadata
    volume_purchasing_program:
      - location: "Fleet (Crystal Skyline)"
        fleets:
          - "💻 Workstations"
          # - "🧪 Workstations (canary)"
          # - "🪪 New Hires"
software:
controls: # This cannot be set here and in unassigned.yml
  windows_enabled_and_configured: true
  macos_settings:
    custom_settings:
      - paths: ./lib/macos/configuration-profiles/*.mobileconfig
      # - path: ./lib/macos/configuration-profiles/AppleScript-PPPC.mobileconfig
      # - path: ./lib/ios/configuration-profiles/lock-screen-message.mobileconfig
      - paths: ./lib/ios/declaration-profiles/*.json
