# For Fleet Free:
# - This file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium:
# - This file updates policies and queries that run on all hosts ("All fleets").
# - Remove "controls" and add this to your YAML files in fleets/ instead.

policies:
  # macOS policies
  - path: ./lib/macos/policies/update-safari.yml
  - path: ./lib/macos/policies/macos-device-health.policies.yml
  - path: ./lib/macos/policies/plist-bit.yml
  - path: ./lib/macos/policies/*.yml
  # Linux policies
  # - path: ./lib/linux/policies/linux-device-health.policies.yml
queries:
  - path: ./lib/macos/queries/detect-apns-certificate.yml
  - path: ./lib/macos/queries/detect-apple-intelligence.yml
  - path: ./lib/macos/queries/network-quality.yml
  - path: ./lib/macos/queries/snowflake-macos-metrics.yml
  - path: ./lib/all/queries/hw-info.yml
  - path: ./lib/all/queries/router-address.yml
  - path: ./lib/all/queries/remote-access.yml
  - path: ./lib/all/queries/collect-mounted-volumes.yml
  - path: ./lib/all/queries/*.yml

agent_options:
  path: ./lib/agent-options.yml
  config:
    decorators:
      load:
        - SELECT uuid AS host_uuid FROM system_info;
        - SELECT hostname AS hostname FROM system_info;
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: "Declarative Management (ds)"
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  features:
    enable_host_users: true
    enable_software_inventory: true
  mdm:
    macos_setup:
      macos_setup_assistant: ./lib/macos/enrollment-profiles/automatic-enrollment.dep.json
    end_user_license_agreement: ./lib/eula.pdf
    end_user_authentication:
      entity_id: fleet
      idp_name: Okta
      metadata_url: https://trial-5568133.okta.com/app/exkxzb4y1mD65dJih697/sso/saml/metadata
    volume_purchasing_program:
      - location: "Fleet (Crystal Skyline)"
        fleets:
          - "⚙️ Engineering"
          - "🖥️ Workstations"
          - "🪪 New Hires"
          # - "Unassigned"
software:
controls: # This cannot be set here and in unassigned.yml
  windows_enabled_and_configured: true
  macos_settings:
    custom_settings:
      - path: ./lib/macos/configuration-profiles/self-service.mobileconfig
      - path: ./lib/macos/configuration-profiles/AppleScript-PPPC.mobileconfig
      - path: ./lib/ios/configuration-profiles/lock-screen-message.mobileconfig
      - path: ./lib/ios/declaration-profiles/swupd-settings.json
