# For Fleet Free:
# - This file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium:
# - This file updates policies and queries that run on all hosts ("All teams").
# - Remove "controls" and add this to your YAML files in teams/ instead.

policies:
queries:
agent_options:
  path: ./lib/agent-options.yml
controls: # This cannot be set here and in no-team.yml
org_settings:
  macos_setup:
    enable_end_user_authentication: true
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: "Don't Panic (ds)"
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  features:
    enable_host_users: true
    enable_software_inventory: true
  mdm:
    end_user_license_agreement: ./lib/eula.pdf
    end_user_authentication:
      entity_id: fleet
      idp_name: Okta
      metadata_url: https://trial-5568133.okta.com/app/exkxzb4y1mD65dJih697/sso/saml/metadata
